Added a Win32 .manifest file and associated .rc file to load version 6 of comctl32.dll for visual themes.  Added winrc.m4 for rules to compile the .rc file. Changed the Makefile to merge in any Microsoft-compiler-created manifest file (for picking the correct MSVCRT).  Changed the theme init code to properly check that comctl32.dll version 6 is actually being used.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -705,6 +705,14 @@ TK_PLATFORM_DIR_NATIVE
 TK_INCLUDES
 XMKMF
 subdirs
+RC
+RC_OUT
+RC_TYPE
+RC_INCLUDE
+RC_DEFINE
+RC_DEPARG
+RES
+MACHINE
 CLEANFILES
 TCL_THREADS
 SHARED_BUILD
@@ -8406,12 +8414,14 @@ esac
 # your system.
 #--------------------------------------------------------------------
 
+OUTPUTFILES=Makefile
+
 if test "${TEA_PLATFORM}" = "windows" ; then
     cat >>confdefs.h <<\_ACEOF
 #define BUILD_treectrl 1
 _ACEOF
 
-    CLEANFILES="pkgIndex.tcl *.lib *.dll *.exp *.ilk *.pdb vc*.pch"
+    CLEANFILES="pkgIndex.tcl *.manifest *.lib *.dll *.exp *.ilk *.pdb vc*.pch"
 
     vars="gdi32.lib user32.lib"
     for i in $vars; do
@@ -8435,6 +8445,167 @@ fi
 	subdirs="$subdirs shellicon"
 
     fi
+
+    # Find rc.exe or windres.exe.
+    # Defined in winrc.m4.
+
+
+#    AC_MSG_CHECKING([for windows resource compiler])
+    if test "${GCC}" = "yes" ; then
+	# Extract the first word of "windres", so it can be a program name with args.
+set dummy windres; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_RC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$RC"; then
+  ac_cv_prog_RC="$RC" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_RC="windres"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+RC=$ac_cv_prog_RC
+if test -n "$RC"; then
+  { echo "$as_me:$LINENO: result: $RC" >&5
+echo "${ECHO_T}$RC" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+	if test "${RC}" = "" ; then
+	    { { echo "$as_me:$LINENO: error: Required resource tool 'windres' not found on PATH." >&5
+echo "$as_me: error: Required resource tool 'windres' not found on PATH." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	RC_OUT=-o
+	RC_TYPE=
+	RC_INCLUDE=--include
+	RC_DEFINE=--define
+	RC_DEPARG='"$<"'
+	RES=res.o
+
+	# Check for a bug in gcc's windres that causes the
+	# compile to fail when a Windows native path is
+	# passed into windres. The mingw toolchain requires
+	# Windows native paths while Cygwin should work
+	# with both. Avoid the bug by passing a POSIX
+	# path when using the Cygwin toolchain.
+
+	if test "$ac_cv_cygwin" = "yes"; then
+	    RC_DEPARG='"$<"'
+	elif test "$CYGPATH" != "echo" ; then
+	    conftest=/tmp/conftest.rc
+	    echo "STRINGTABLE BEGIN" > $conftest
+	    echo "101 \"name\"" >> $conftest
+	    echo "END" >> $conftest
+
+	    { echo "$as_me:$LINENO: checking for Windows native path bug in windres" >&5
+echo $ECHO_N "checking for Windows native path bug in windres... $ECHO_C" >&6; }
+	    cyg_conftest=`$CYGPATH $conftest`
+	    if { ac_try='$RC -o conftest.res.o $cyg_conftest'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } ; then
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		RC_DEPARG='"$(shell $(CYGPATH) $<)"'
+	    else
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	    fi
+	    conftest=
+	    cyg_conftest=
+	fi
+
+    else
+	if test "$do64bit" != "no" ; then
+	    RC="\"${MSSDK}/bin/rc.exe\""
+	elif test "$doWince" != "no" ; then
+	    RC="\"${WCEROOT}/Common/EVC/bin/rc.exe\""
+	else
+	    RC="rc"
+	fi
+	RC_OUT=-fo
+	RC_TYPE=-r
+	RC_INCLUDE=-i
+	RC_DEFINE=-d
+	RC_DEPARG=='"$<"'
+	RES=res
+    fi
+
+
+
+
+
+
+
+
+
+
+    # X86|AMD64|IA64 for manifest
+
+
+    # Create treectrl.dll.manifest from treectrl.dll.manifest.in.
+    # treectrl.dll.manifest is included by treectrl.rc.
+    # If building with a Microsoft compiler that generates
+    # treectrlNN.dll.manifest (to pick the correct MSVCRT runtime) then
+    # that manifest is merged with mine using mt.exe (see the Makefile
+    # rule for PKG_LIB_FILE).
+    OUTPUTFILES="Makefile treectrl.dll.manifest"
+
+
+    vars="treectrl.rc"
+    for i in $vars; do
+	case $i in
+	    \$*)
+		# allow $-var names
+		PKG_SOURCES="$PKG_SOURCES $i"
+		PKG_OBJECTS="$PKG_OBJECTS $i"
+		;;
+	    *)
+		# check for existence - allows for generic/win/unix VPATH
+		if test ! -f "${srcdir}/$i" -a ! -f "${srcdir}/generic/$i" \
+		    -a ! -f "${srcdir}/win/$i" -a ! -f "${srcdir}/unix/$i" \
+		    ; then
+		    { { echo "$as_me:$LINENO: error: could not find source file '$i'" >&5
+echo "$as_me: error: could not find source file '$i'" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+		PKG_SOURCES="$PKG_SOURCES $i"
+		# this assumes it is in a VPATH dir
+		i=`basename $i`
+		# handle user calling this before or after TEA_SETUP_COMPILER
+		if test x"${RES}" != x ; then
+		    j="`echo $i | sed -e 's/\.[^.]*$//'`.${RES}"
+		else
+		    j="`echo $i | sed -e 's/\.[^.]*$//'`.\${RES}"
+		fi
+		PKG_OBJECTS="$PKG_OBJECTS $j"
+		;;
+	esac
+    done
+
+
+
 else
     CLEANFILES="pkgIndex.tcl"
 fi
@@ -12134,7 +12305,7 @@ echo "${ECHO_T}${WISH_PROG}" >&6; }
 # which require substituting th AC variables in.  Include these here.
 #--------------------------------------------------------------------
 
-ac_config_files="$ac_config_files Makefile"
+ac_config_files="$ac_config_files $OUTPUTFILES"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -12691,7 +12862,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF
 for ac_config_target in $ac_config_targets
 do
   case $ac_config_target in
-    "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+    "$OUTPUTFILES") CONFIG_FILES="$CONFIG_FILES $OUTPUTFILES" ;;
 
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
@@ -12901,6 +13072,14 @@ TK_PLATFORM_DIR_NATIVE!$TK_PLATFORM_DIR_NATIVE$ac_delim
 TK_INCLUDES!$TK_INCLUDES$ac_delim
 XMKMF!$XMKMF$ac_delim
 subdirs!$subdirs$ac_delim
+RC!$RC$ac_delim
+RC_OUT!$RC_OUT$ac_delim
+RC_TYPE!$RC_TYPE$ac_delim
+RC_INCLUDE!$RC_INCLUDE$ac_delim
+RC_DEFINE!$RC_DEFINE$ac_delim
+RC_DEPARG!$RC_DEPARG$ac_delim
+RES!$RES$ac_delim
+MACHINE!$MACHINE$ac_delim
 CLEANFILES!$CLEANFILES$ac_delim
 TCL_THREADS!$TCL_THREADS$ac_delim
 SHARED_BUILD!$SHARED_BUILD$ac_delim
@@ -12929,7 +13108,7 @@ WISH_PROG!$WISH_PROG$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 37; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 45; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
